$schema: "./config.schema.json"

open_ticket_ai:

    # only one ticket-system adapter
    system:
        server_address: "http://52.57.217.182/otobo/nph-genericinterface.pl"
        webservice_name: "OpenTicketAI"
        search_operation_url: "ticket-search"
        update_operation_url: "ticket-update"
        get_operation_url: "ticket-get"
        username: "openticketai_ws"
        password_env_var: "OTOBO_DEMO_PASSWORD"

    filter_by_queue: "Raw"

    hf_model: "Tobi-Bueck/atc-queue-model"
    hf_token_env_var: "HUGGINGFACE_TOKEN"

    confidence_threshold: 0.8
    low_confidence_queue: Junk

    run_every_seconds: 10
