name: Build and Publish open-ticket-ai-hf-local
permissions:
  contents: read

on:
  push:
    tags:
      - 'hf-local-v*'
      - 'otai-hf-local-v*'
  workflow_dispatch:
jobs:
  publish:
    uses: ./.github/workflows/publish-to-pypi.yml
    with:
      package-name: otai-hf-local
      package-path: packages/otai_hf_local
    secrets:
      PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
